app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/AssistanceContactsResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/BusinessResourceIC.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/CertifiedFieldResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/GeographicTaxonomyListResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/GeographicTaxonomyResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionLegalAddressResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionOnboardingInfoResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionResourceIC.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/MatchInfoResultResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/ProductResource.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/UserResource.java
Removed validation constraints on resources.
It's not necessary to have validation on response objects. This validation is only available for incoming requests and dtos.
I have started the ms-product-microservice and onboarding-microservice in local aiming dev db and then I have added a new product into mongo collection with missing fields. No error was returned in response.
=> Removed validation constraints on resources

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/exceptions/InternalGatewayErrorException.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/decoder/FeignErrorDecoder.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/rest/decoder/FeignErrorDecoderTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/handler/OnboardingExceptionHandler.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionControllerTest.java
Retrieve fiscal code from jwt token to invoke infocamere @POST /instituions. No needed to receive a body so this endpoint is deprecated Moving to GET /institutions/from-infocamere/
Get institutions from infocamere must be called only from user logged. Fiscalcode will be retrieved from jwt token.
Try call POST /onboarding/v1/instituions without body
Try call GET  /onboarding/v1/institutions/from-infocamere/
=> Refactor: retrieve institutions from infocamere

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
handle null geotax list when institution connector return an institution that does not have geotax.
Throw a NullPointerException when call GET /institutions/{externalInstitutionId}/geographicTaxonomy on an institution that does not have geotax and http response returned 500
Try to call GET /institutions/{externalInstitutionId}/geographicTaxonomy on an institution that does not have geotax. It must not return http 500 error core.
=> fix: handle null geotax list when institution does not have geotax

connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/exceptions/InvalidRequestException.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/decoder/FeignErrorDecoder.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/handler/OnboardingExceptionHandler.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/handler/OnboardingExceptionHandlerTest.java
- add statusCode 400 in FeignErrorDecoder
- add InvalidRequestException
- add tests for exceptionhandler 
- Need to catch error 400 in FeignErrorDecoder 
- try to call /onboarding/v1/institutions/{vatNumber}/match with FLNDVD98L15H501X, 42947449007, this call have to return httpStatus 400
=> SELC-2716 add statusCode 400 in FeignErrorDecoder

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
Added ADE and INFOCAMERE to origins that do not require LocationInfo when onboarding product
ADE and INFOCAMERE origins are used in the context of PNPG onboarding and do not require location data
local environment
=> [SELC-3375] Fix: Added ADE and INFOCAMERE to origins that do not require LocationInfo 

.github/workflows/release_open_api.yml
Added openapi-diff step into Github action to detect breaking changes.
In order to detect incompatible changes between the branch of release-dev and the branch of any new developmen, it has been added into githib action a step that check differences between the two open api. In particular:
- The step will cause the failure of github action in case of deletion of attribute from resources
- The step will cause the failure of github action in case of renaming of attribute from resources
- No failure in case of new attribute added in resources
=> [SELC-3416] feat: added github action to detect breaking changes into open api

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Added mapping to populate institution location for those non ipa institutions that were already persisted on selfcare
The location informations of non IPA institutions that were already persisted on selfcare weren't retrieved properly, hence when the getInstitutionOnboardingInfo api gets called they weren't returned correctly. Prompting the FE to ask for those informations again from the user
Tested Locally
=> retrieve location data correctly for non IPA institution

app/src/main/resources/swagger/api-docs.json, helm/pnpg/values-dev.yaml, helm/pnpg/values-prod.yaml, helm/pnpg/values-uat.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/ProductController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/ProductControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java
* Remove /v1 prefix at helm file
* Added /v1 prefix to web controller
/v1 prefix at helm value does not permit to add a new version of the endpoint, for example /v2/onboarding. Moving the prefix to controller enable possibility to create a new version of web controllers.
=> ops: move /v1 from helm to controller

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingMode.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
* Added **TokenV2Controller** which implements the new call to onboarding-ms for '_onboarding complete_'.
* Added **InstitutionV2Controller** which implements the new call to onboarding-ms for '_onboarding_'.
* Remove OnboardingMove because it is replaced with new endpoint for invoking new onboarding complete
This change is required to integrate the new onboarding flow with the onboarding-ms service. The introduction of **TokenV2Controller** and **InstitutionV2Controller** is crucial for implementing the new logic while maintaining backward compatibility. The new endpoints in these controllers will handle the updated onboarding process, ensuring a seamless transition to the new system without disrupting existing functionality.
=> [SELC-3452] feat: added V2 for new onboarding request

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
**Verify Endpoint V2 using new Onboarding**: Added a new endpoint /v2/tokens/{onboardingId}/verify that returns an onboardingId record by its ID only if its status is PENDING otherwise it will return 404. This feature is crucial for ensuring that the onboarding process can be completed only when the onboarding status is appropriately set to PENDING.
The addition of this endpoints is driven by the need for the front-end to effectively verify the status of an onboarding process using new onboarding services. This endpoint ensures that the onboarding process adheres to the necessary workflow, where completion is contingent upon the onboarding status being PENDING.
=> [SELC-3509] feat: using new endpoints V2 for Onboarding Process Verification

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Replaced control criteria that allowed an onboarding request to create an institution from IPA. Now based on the presence and value of the subunitType field the party-registry API is called to check that the institution is actually present on IPA before initiating a creation with the respective API
The change was necessary because some GPS institutions did not fit the previous control criteria, based on institutionType, and therefore were created with SELC origin. Whereas with the change we are able to figure out if the institution you are trying to onboard is present on IPA, and contextually we can create it through the appropriate API.
Local environment
=> [SELC-1891] - feature: Added check to see if institution is present on ipa before calling create from ipa API

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
* Added a new endpoint, version v2 /reject, which is designed to process reject for certain types of institutions during the onboarding process.
* This endpoint triggers the new onboarding service
This change is necessary to streamline the onboarding process for specific types of institutions that require administrative rejection. The existing onboarding process redirect to old onboarding service.
=> [SELC-3493] feat: Introduce New v2 /reject Endpoint for admin Onboarding Workflow

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/AdditionalInformations.java, connector/rest/src/test/resources/stubs/party-process/mappings/getUserInstitutionRelationships_fullyValued.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/AdditionalInformationsDto.java, web/src/main/resources/swagger/swagger_en.properties
- change isAgentOfPublicService and isIpa to agentOfPublicService and ipa 
The mentioned fields names ("isIpa" and "isAgentOfPublicService") were not reconized.
=> [SELC-3790] fix: change field name isIpa and isAgentOfPublicService

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/MsOnboardingTokenApiClient.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/MsOnboardingApiClientConfig.java, connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
- add API getContract
- align ms-onboarding open-api
- align onboarding-backend open-api
- add unit tests
The implementation of this API was necessary because the contract will no longer be attached to email sent to institution, but it will be possible to download it through the same FE page where the upload button is also present.
Onboarding BFF and onboarding were started locally, then the API was invoked and it was verified that the contract was correctly retrieved.
=> feat: [SELC-4354] add API getContract to download an onboarding request's contract

app/src/main/resources/config/application.yml, connector/rest/pom.xml, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, helm/pnpg/values-prod.yaml, helm/values-prod.yaml
Added retry using resilience4j when an Timeout occurred
Mitigation issue with new Container App Environments
=> hotfix: added retry for onboarding ms client

web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- Added Content-Disposition header
- In order to read the previous one, a new header has been added to the response entity: ACCESS_CONTROL_EXPOSE_HEADERS
These changes have been implemented in order to allow clients to read the name of file given as response from the API
=> [SELC-4354] fix: Added headers to the Response Entity

connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
updated selfcare-onboarding openapi adding originId field in new onboarding API, and mapped originId field with ivassCode in DTOs 
It is necessary to add the originId field and map it to the ivassCode for onboarding foreign insurance in the objects used by the onboarding API
local env
=> SELC-4720 feature: added originId mapping using ivassCode

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClient.java, connector/rest/src/main/resources/config/party-process-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, pom.xml, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
* refactor endpoint GET /institutions/onboarding replacing path parem taxcode with institutionId
* Updated any related tests to accommodate the new implementation.
This endpoint is used only for onboarding prod-io-premium. This [PR](https://github.com/pagopa/selfcare-onboarding-backend/pull/307) has done an refactor where frontend retrieve a list of institutions with institutionId instead of taxCode.
=> [SELCA-4947] feat: refactor getInstitutionOnboardingData using institutionId

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
* Updated ApiOperation annotations that has changed to include a custom operationId.
* Ensured that these endpoint has a previous operationId to prevent naming conflicts and ensure smooth updates on APIM.
This pull request introduces a custom **operationId** within the `ApiOperation` annotations to ensure consistent updates of our APIs on Azure API Management (APIM). The custom operationId is crucial to avoid issues that arise when the operationId changes, which can prevent the API from updating correctly. Without a custom operationId, renaming an operationId necessitates deleting and recreating the entire API group, leading to temporary service disruptions and loss of analytics data.
=> chore: Set Custom Operation ID for ApiOperation Annotations

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingUserDto.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java, web/src/test/resources/stubs/onboardingUsers.json
Added API to start onboarding for new users
This functionality has been added to allow the addition of new administrators for a previous onboarding.
I have run the microservice locally and tested the API **POST/users/onboarding**
=> [SELC-4374] feat: added API to start onboarding for new users

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionUpdate.java, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, connector/rest/src/test/resources/stubs/party-process/mappings/getUserInstitutionRelationships_fullyValued.json, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/mapper/InstitutionInfoMapper.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/InstitutionMapper.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
- Added institution id into response in order to display logo
- Changed response from single object to List
- Added filter to retrieve unique entity in case of research for only taxCode
In order to display logo, the API that retrieves the onboardings should contain, into institution data, an identifier of this entity
=> [SELC-4371] fix: Added institution id into response in order to display logo

connector/rest/docs/openapi/api-selfcare-onboarding-functions-docs.json, connector/rest/pom.xml, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/OnboardingFunctionsApiClient.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/OnboardingFunctionsClientConfig.java, connector/rest/src/main/resources/config/onboarding-functions-rest-client.properties
1. Added swagger for onboarding functions to invoke checkOrganization api.
2. Added client feign and configurations.
The checkOrganization api was created as an http azure function on ms-onboarding for phasing out functions from external interceptor
local env
=> [SELC-4903] feat: added OnboardingFunctionsApiClient and codegen execution in pom

connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingFunctionsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-functions-docs.json, connector/rest/pom.xml, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingFunctionsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/OnboardingFunctionsApiClient.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/OnboardingFunctionsClientConfig.java, connector/rest/src/main/resources/config/onboarding-functions-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingFunctionsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Replaced external-interceptor connector with onboarding-functions connector in service for checkOrganization API
The checkOrganization api was created as an http azure function on ms-onboarding for phasing out functions from external interceptor. So we need to call the new endpoint
local env
=> [SELC-4903] feat: replaced external-interceptor connector with onboarding-functions connector

infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
added env var to call onboarding-functions api
The checkOrganization api was created as an http azure function on ms-onboarding for phasing out functions from external interceptor. So we need to call the new endpoint
local env
=> [SELC-4903] feat: added env var to call onboarding-functions api

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
updated verifyOnboarding invocation to OnboardingMS
the invocation towards OnboardingMS has been changed instead of Core as verifyOnboarding should be the domain of the Onboarding MS
the API was invoked locally by doing several tests. Multiple input parameters were passed looking for different types of entities for different products
=> [SELC - 5350] feat: updated verifyOnboarding invocation to OnboardingMS

app/src/main/resources/swagger/api-docs.json, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
added check that only the productId is not passed
To prevent the frontend from passing only the productId as a parameter for verifyOnboarding and returning 204, a control has been added so that 400 is returned
the microservice was started locally and only the productId was passed in order to verify that a 400 was returned instead of 204
=> [SELC - 5484] feat: added check that only the productId is not passed

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
added check on infocamere to prevent user which is not LR to onboard the PG
Without this feature, any user invoking the API could onboard the business even if is not Manager on Infocamere. Because actually the check is present only on frontend.
local env
=> [PNPG-224] feat: added check on infocamere to prevent user which is not LR to onboard the PG

infra/container_apps/main.tf
Fix of this https://pagopa.atlassian.net/wiki/spaces/DEVOPS/pages/463241875/Terraform+Troubleshooting+FAQs#%5CuD83E%5CuDD14-Problem%3A-Error-ensuring-Resource-Providers-are-registered.
=> fix: add skip_provider_registration true

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Added logic to remove institutions already onboarded in getInstitutionsFromInfocamere.
With this feature when the user on PNPG wants to perform onboarding of institutions from infocamere will receive on page only institutions that are not already onboarded by him.
local env
=> [PNPG-218] feat: added logic to remove institutions already onboarded in getInstitutionsFromInfocamere

core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
changed prod-pnpg to prod-pn-pg when invoking api to check if onboarding is already active.
The productId was wrong. The correct one in this case is prod-pn-pg
=> [PNPG-218] fix: changed prod-pnpg to prod-pn-pg

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- Updated selfcare onboarding openapi and related API
- Added vatNumber in VerifyAggregatesResponse.aggregates
For the contract of the aggregating entities, it is necessary to include all the data of the aggregated entities, both those retrieved from IPA and those sent via CSV and not overwritten by IPA. Therefore, it is essential that all this data is available during the initial persistence.
=> [SELC-5668] Feat: added vatNumber in VerifyAggregatesResponse.aggregates

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/CheckManagerResponse.java, web/src/main/resources/swagger/swagger_en.properties
added dedicate response object for check-manager API
Previously the API had a response formed by a map, but it created problems for frontend codegens. So we created a dedicated object.
=> [PNPG-263] feat: added dedicate response object for check-manager API

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/ManagerVerification.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/VerifyManagerRequest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/VerifyManagerResponse.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
Added api /company/verify-legal to check if user is manager of given company on external registries
With this API, it is possible to check whether a user is a legal representative on the records of infocamere and ADE. It returns 404 if the verification fails
local nev
=> [SELC-6113] feat: Added api /company/verify-legal to check if user is manager of given company on external registries

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java, web/src/main/resources/swagger/swagger_en.properties
Added attribute attachments into response for API v2/tokens/{onboardingId} 
This change is necessary to provide list of attachments linked to an onboarding.
I have deployed the feature branch in DEV and tested the API GET v2/tokens/{onboardingId}
=> [SELC-6133] feat: added attribute attachments into response for API v2/tokens/{onboardingId} 

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/ManagerInfoResponse.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/UserResourceMapper.java, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java
added API to retrieve manager info given onboardingId
This API is needed to find out the personal information of the manager who performed the membership of a given company on PNPG. In fact, internally it has control logics that allow the manager's personal data to be received in response, only if the user invoking the API is already ADMIN of the company or is LR on Infocamere and ADE registries.
local env
=> [SELC-6181] feat: added API to retrieve manager info given onboardingId

core/src/main/java/it/pagopa/selfcare/onboarding/core/ProductServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/ProductServiceImplTest.java
Changed the response for api v1/product/{productId} to 404 in case of product not found
If the productId passed in input does not exist, the API will return 404 as response.
I have started the ms locally and tested both scenarios (with wrong and correct identifier)
=> [SELC-6077] feat: return 404 in case product not found

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/UserRegistryConnector.java, connector/rest/docs/openapi/api-user-registry-docs.json, connector/rest/pom.xml, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/UserRegistryConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/UserRegistryRestClient.java, connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/UserMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/UserRegistryConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java, core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/UserTaxCodeDto.java, web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/UserResourceMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java
- Added api to retrieve uuid from PDV
- added open api generator for PDV
This API returns the user's uuid during the onboarding phase that will be used later by the already implemented check-manager. If the API returns 404 (not present on PDV) the second call will not be made
MS was started locally and the API was invoked to see if everything was working correctly
=> [SELC-6954] feat: Added api to retrieve uuid from PDV
