pagopa/selfcare-onboarding-backend

- app/src/main/resources/config/application.yml
- app/src/main/resources/swagger/api-docs.json
- pom.xml
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> add json log format and one-line exception logging (#48)

- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- remove logic for set the same manager as the base product
- add check if base product is already onboarded
> changes on onboarding premium process

- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- remove logic for set the same manager as the base product
- add check if base product is already onboarded
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> release-uat

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionType.java
- pom.xml
* add PSP to InstitutionType enum
* update commons version
> add PSP to InstitutionType enum (#63)

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/ProductResource.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/ProductMapper.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/model/ProductResourceTest.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/model/mapper/ProductMapperTest.java
* Modified API to retrieve a product in the onboarding phase, the API now also displays the "status" field
* Modified API to retrieve a product in the onboarding phase, the API now also displays the "status" field
* Modified API to retrieve a product in the onboarding phase, the API now also displays the "status" field
* Modified API to retrieve a product in the onboarding phase, the API now also displays the "status" field
> Release uat

- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Reverts pagopa/selfcare-onboarding-backend#89
> Revert "Feature/selc 1852"

- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- pom.xml
Reverts pagopa/selfcare-onboarding-backend#88
> Revert feature/SELC-1843

- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
…eInstitutionFromIpa (#132)
* fix: remove createFromIpa on onboarding by externalId
* fix: set InstitutionFromIpaPost to restClient.createInstitutionFromIpa
> fix: set InstitutionFromIpaPost to restClient.createInstitutionFromIpa

- .github/PULL_REQUEST_TEMPLATE.md
- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClient.java
- connector/rest/src/main/resources/config/party-process-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClientTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitution.json
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
> fix: on onboarding replaced createInstitutionRaw to createInstitution when institutionType is not PA

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
add imprese.{env}.notifichedigitali.it to cors-allow-origin in pnpg/helm
pnpg moved url from pnpg.selfcare.it to imprese.notifichedigitali.it
Navigate to imprese.notifichedigitali.it
> ops: add imprese.env.notifichedigitali.it to cors-allow-origin

- helm/values-prod.yaml
1. update file values-prod.yaml to abilitate io-sign product
since the io-sign product is no longer in testing we need to allow entities to onboard the product
> feat: Enabling the io-sign product in prod

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenController.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenControllerTest.java
added endpoint DELETED /tokens/{tokenId}/complete for proxy core to delete complete token
Isolate from external core microservice
execute DELETED /tokens/{tokenId}/complete
> feat: added proxy core to delete complete token

- helm/pnpg/values-prod.yaml
- helm/values-prod.yaml
set REST_CLIENT_READ_TIMEOUT to 30 sec in prod
set REST_CLIENT_CONNECT_TIMEOUT to 30 sec in prod
Onboarding request takes a long time, increasing timeout is a temporary solution before moving to async handling
> ops: increase read and connection timeout of rest clients

- helm/pnpg/values-prod.yaml
- helm/values-prod.yaml
set REST_CLIENT_READ_TIMEOUT to 30 sec in prod conf
set REST_CLIENT_CONNECT_TIMEOUT to 30 sec in prod conf
Onboarding request takes a long time, increasing timeout is a temporary solution before moving to async handling
> ops(merge-back-main): increase read connection timeout

- helm/values-prod.yaml
Removing prod-io and prod-io-premium from config map
Due to App IO maintenance, Selfcare don't allow to onboard prod-io and prod-io-premium products
> App IO maintenance

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfig.java
add NOT_FOUND and CONFLICT in SwaggerConfig for HttpMethd POST
Need to add HttpStatus NOT_FOUND and CONFLICT for generated swagger
> SELC-2428 add NOT_FOUND and CONFLICT in SwaggerConfig

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
Added return institution data when onboarding company
PNPG need to know institutionId after onboarding
Try an onbonarding anche check if body response contains institutionId
> refactor: return institution data when onboarding company

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionData.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingMapper.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
Remove get institution when onboarding
Added institutionId on GET /onboarding
PNPG need to know institutionId after onboarding
Try to call GET /institutions/onboarding anche check if body response contains institutionId
> Added institutionId on GET /institutions/onboarding

- helm/values-dev.yaml
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
Enable onboarding for prod-fd-garantito
Fideiussioni Digitali needs to onboard PA's as guaranteed entities to their backoffice
> enable onboarding for prod-fd-garantito

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/BillingDataResponseDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionData.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingMapper.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
* Create BillingDataResponseDto as output for onbordingInfo 
OnbordingInfo return BillingData which have required attributes as output
> refactor: billingdataresponse as output @onbordingInfo 

- helm/values-uat.yaml
remove prod-fd from uat allowed list
prod-fd is not ready to be onboarded in this environment
> remove prod-fd from uat alllowed list

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClient.java
- connector/rest/src/main/resources/config/party-process-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Added logic to complete onboarding for AS
Into onboarding process, it was necessary to add check for new institutionType AS. For insurances, a new endpoint of ms-core is invoked.
I have deployed the feature branch in DEV environment and tested the onboarding process for AS.
> [SELC-3232] feat: added logic to complete onboarding for AS

- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
make controll on verify type nullsafe
make controll on verify type nullsafe
> make controll on verify type nullsafe

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/pnpg-code-review-pipelines.yml
- .devops/pnpg-deploy-pipelines.yml
- Dockerfile
- pom.xml
List of Changes
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
- updated dockerfile image
These updates are necessary as there is a need to upgrade to java 17
- Build was done locally
- the microservice was started locally and some APIs were invoked
> [SELC-3371] feat: Update to jdk 17

- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
* Fix onboarding ms url on helm files
* Fix mapper institution onboarding v2
> [SELC-3452] fix: mapper onboarding v2

- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
Fix map business name to description on onboarding V2
> fix: map business name onboarding V2

- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
discard old mapper use for mapstruct
Some fields were not mapped correctly in the response return throwing a nullpointer exception
Deployed to dev environment and tested with FE
> Implement mapstruct mapper for InstitutionOnboardingInfoResource

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
* Added a new endpoint, version v2 /approve, which is designed to process approvals for certain types of institutions during the onboarding process.
* This endpoint triggers the new onboarding service, facilitating the completion of the onboarding workflow upon receiving admin approval.
This change is necessary to streamline the onboarding process for specific types of institutions that require administrative approval. The existing onboarding process redirect to old onboarding service.
> [SELC-3493] feat: Introduce New v2 /approve Endpoint for admin Onboarding Workflow

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
* Added a new endpoint, version v2 DELETE /tokens/complete, which is designed to process delete onboarding request.
* This endpoint triggers the new onboarding service
This change is necessary to streamline the onboarding process when a user want to delete an onboarding request. The existing onboarding process redirect to old onboarding service.
> [SELC-2865] feat: Introduce New v2 DELETE tokens/complete Endpoint

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java
Remove required on manager when get onboarding
Manager is not mandatory in some scenarios
> fix: remove required manager when get onboarding

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
* Added a new endpoint, version v2 POST onboarding/company, which is designed to process onboarding request for PG institution.
* This endpoint triggers the new onboarding service
The existing onboarding process redirect to old onboarding service.
> [SELC-3996] feat: Introduce New v2 onboarding/company Endpoint

- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
Update onboarding openapi
API onboarding remove recipientCode as mandatory
> [SELC-3922] feat: update onboarding openapi

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
Set MS_ONBOARDING_URL value for PNPG
> [SELC-3996] ops: MS_ONBOARDING_URL value for PNPG

- .github/workflows/opex_api_pnpg.yml
- .opex/api-selfcare-onboarding-pnpg/env/prod/backend.ini
- .opex/api-selfcare-onboarding-pnpg/env/prod/backend.tfvars
- .opex/api-selfcare-onboarding-pnpg/env/prod/config.yaml
- .opex/api-selfcare-onboarding-pnpg/env/prod/terraform.tfvars
> [SELC-2952] feat: add opex to pnpg

- .opex/api-selfcare-onboarding-pnpg/env/prod/config.yaml
- .opex/api-selfcare-onboarding/env/prod/config.yaml
> [SELC-2952] fix alert

- .opex/api-selfcare-onboarding-pnpg/env/prod/config.yaml
- .opex/api-selfcare-onboarding/env/prod/config.yaml
> [SELC-2952] fix Endpoints configuration

- app/src/main/resources/swagger/api-docs.json
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java
> Release dev

- .github/workflows/release_ms_pnpg.yml
> [EC-159] Add PNPG release workflow

- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
fix openapi of onboarding-ms removing pattern mail on onboarding pg request
> fix: pattern mail on onboarding pg request

- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
Mapping business name using institutionUpate when onboarding company
Previous mapping used wrong attribute
> fix: mapping company name

- helm/pnpg/values-prod.yaml
- helm/values-prod.yaml
> ops: set onboarding ms url prod

- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
JWT_TOKEN_PUBLIC_KEY misses as env variable
> [EC-128] fix: added JWT_TOKEN_PUBLIC_KEY as secret

- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
Restored deprecated API onboarded-institution-info
This API has been restored because it is still used by frontend side
> fix: Restored deprecated API onboarded-institution-info

- infra/container_apps/.terraform.lock.hcl
- infra/container_apps/apim.tf
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/variables.tf
Added apim group BFF onboarding for migration to Container Apps
> [SELC-4511] Added apim group BFF onboarding for ca

- helm/values-prod.yaml
adding new fields to ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS config map
> ADD PROD-FD and PROD-FD-GARANTITO to prod env

- helm/values-dev.yaml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Migration to Container App DEV supporting a workload profile
> chore: Workload profiles migration DEV

- .github/workflows/release_open_api.yml
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-uat.yaml
- helm/values-uat.yaml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Remove workload_profile_name variables because is default on terraform module
Change PNPG dns suffix url
Migration to new Container Apps environment with Workload profile
> chore: Workload profiles migration PNPG

- infra/container_apps/apim.tf
Expose headers from base policy
If not header are exposed react FE can't detect file name from getContract API
> [SELC-4354] Expose headers from apim

- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- infra/container_apps/README.md
- infra/container_apps/apim.tf
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
* Container App env name must be specified
* workload_profile null for dev and prod
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/BillingDataDto.java
- Removal of mandatory zipCode
Change required for foreign insurance onboarding
> [SELC - 4465 -fix] feat: Removal of mandatory zipCode

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
removed NotNull from billingData
We need to remove the NotNull from billingData because we need to allow onboarding process to Institution without vatNumber
> SELC-4474 fix: removed NotNull from billingData

- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java
> Remove vatNumber as mandatory field

- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
> hotfix: remove pattern digitalAddress

- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
https://pagopa.atlassian.net/wiki/spaces/SCP/pages/1051951216/Piattaforma+Unitaria
> Onboarding new product prod-piattaforma-unitaria

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/Billing.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClientTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/getOnBoardingInfo_fullyValued.json
- connector/rest/src/test/resources/stubs/party-process/mappings/getUserInstitutionRelationships_fullyValued.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
Added taxCodeInvoicing to billing node of Institution object
> [SELC-4918] feat: Added taxCodeInvoicing to billing node of Institution object

- app/src/main/resources/swagger/api-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/ReasonForRejectDto.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Removed NotNull annotation on field reason in case of onboarding's rejection
> [SELC-4829] feat: Removed constraint on field reason in case of onboarding reject

- .github/workflows/pr_ms.yml
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java
- connector/rest/docs/openapi/api-selfcare-user-docs.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/MsUserApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/MsUserApiClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/InstitutionMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/OnboardingResponse.java
- connector/rest/src/main/resources/config/ms-user-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyProcessRestClientTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
* Removed the usage of **getOnboardingInfo** in the getInstitutions method.
* Implemented a new call to the **user-ms** microservice to fetch the necessary information about the user's institutions.
* Updated any related tests to accommodate the new implementation.
This PR refactors the **getInstitutions** method to retrieve the list of institutions for a user by calling the user-ms microservice instead of using the outdated **getOnboardingInfo** method. The previous approach is no longer valid following the migration to the user-ms microservice.
> [SELC-4947] feat: refactor getInstitutions method to use user-ms Microservice

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
- web/src/main/resources/swagger/swagger_en.properties
…request
Added originId to onboarding model
When an institution requests to subscribe to a product, after populating the web wizard, they receive a PDF document to sign digitally using the p7m format. This PDF document includes the originId, such as the IPA code for Italian public administrations. Currently, after some self-care refactoring, this field is not present in the internal database.
> [SELC-4816] feat: Added originId to Onboarding model when starting an onboarding

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
- added API to complete users onboarding
this API has been added which invokes the onboarding-be API which is used to complete a user's onboarding request after the contract is loaded
the API was invoked and it was verified that the request was updated to COMPLETED and that the records in userInstitution and userInfo were created in the user DB
> [SELC - 4376] feat: added API to complete users onboarding

- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
Storing an onboarding reject reason when user delete an onboarding request
Avoiding send email confirmation when user delete an onboarding request
> feat: Added reason to track when user reject an onboarding

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/AggregateInstitution.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
- web/src/test/resources/stubs/onboardingProductsDtoWithAggregates.json
- Added isAggregator and aggregates fields in OnboardingProductDto
We need to add these fields for aggregator onboarding process
> [SELC-5075] Feat: Added isAggregator and aggregates fields in OnboardingProductDto

- infra/container_apps/apim.tf
> [APIM-v2 MIGRATION] change reference to apim-v2

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionUpdate.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/getUserInstitutionRelationships_fullyValued.json
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/mapper/InstitutionInfoMapper.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/InstitutionMapper.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
- Added origin and originId into response for getOnboardingInstitutions API
- Removed validation in case of null subunitCode
These changes were necessary to complete onboarding users (USERS workflow)  from Dashboard section
It was already tested in DEV and on main branch
> Merge fix/selc 4371 into release 1.0.9

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/InstitutionMapper.java
Added parentDescription into response object 
This change is necessary in order to display parent description in addition to AOO/UO description for onboarding USERS
> [SELC-5126] fix : Added parentDescription into response object 

- infra/container_apps/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/RowErrorResponse.java
- Added json property in RowErrorResponse
FE needs to have the error data for the rows with the field names in Italian.
> [SELC-5359] Feat: Added json property in RowErrorResponse

- app/src/main/resources/swagger/api-docs.json
- connector-api/pom.xml
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- core/pom.xml
- pom.xml
- web/pom.xml
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/CompanyOnboardingDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingUserDto.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/model/CompanyOnboardingDtoTest.java
Updated references of onboarding-sdk and selfcare-commons to include new institutionType
> [SELC-5407] feat: Updated references of onboarding-sdk and selfcare-commons to include new institutionType

- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
Updated api docs to include enum value PDND_INFOCAMERE
> [selc-5409] fix: Updated api docs to include enum value PDND_INFOCAMERE

- core/pom.xml
- web/pom.xml
Updated sdk dependency version
> [SELC-5497] fix: Updated sdk dependency version

- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- core/pom.xml
- web/pom.xml
> Merge main into releases/1.0.13

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
- Refactor api to verify csv to call different onboarding-ms's APIs based on productId
We need to do different check on aggregates csv based on productId
> [SELC-5471] Feat: Refactor api to verify csv to call different onboarding-ms's APIs based on productId

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/AggregateResult.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/AggregateUserResult.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/VerifyAggregateResult.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/AggregateInstitution.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/VerifyAggregatesResponse.java
- Updated selfcare onboarding openapi and related API](https://github.com/pagopa/selfcare-onboarding-backend/pull/354/commits/5d16527f3246b687a0380f4fe4173fdd7c2ee546)
For the contract of the aggregation entities, it is necessary to include all the data of the aggregated entities, both those retrieved from IPA and those sent via CSV and not overwritten by IPA. Therefore, it is essential that all this data is available during the initial persistence.
> [SELC-5692] Feat: Updated selfcare onboarding openapi and related API

- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionOnboarding.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/InstitutionResponse.java
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitution.json
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitutionUsingExternalId.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionOnboardingResource.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/model/InstitutionOnboardingResourceTest.java
Added and edited models required for new getActiveOnboarding API which will be implemented in other PR
> [PNPG-243] feat: added and edited models required for new getActiveOnboarding API

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
Added on the method checkRecipientCode new apim group for billing-portal
[SELC-5716](https://pagopa.atlassian.net/browse/SELC-5716)
[SELC-5716]: https://pagopa.atlassian.net/browse/SELC-5716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5716] feat: Added tag billing-portal on checkRecipientCode

- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
updated onboarding openapi and check-manager invocation
check-manager api changed the response object, so we are aligning the microservice to obtain and process this new kind of response
> [SELC-5818] feat: updated onboarding openapi and check-manager invocation

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/CompanyOnboardingUserDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
added api onboarding/users/pg
This api will invoke an api with same name on selfcare-onboarding module.
> [PNPG-245] feat: added api onboarding/users/pg

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/AggregateResult.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- Added parentDescription in AggregateResult
- Updated selfcare-onboarding openapi
- Added parentDescription in AggregateResult for API to verify csv
> [SELC-5878] Feat: Added parentDescription in AggregateResult

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java
- add API onboardingAggregator
- add unit tests
This new endpoint is required to manage users addiotion for aggregators with module signature
It was tested locally
> [SELC-5787] feat: add API onboardingAggregator to add new users for aggregators with module signature

- connector-api/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/ProductsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/ProductsConnectorImplTest.java
- core/pom.xml
- core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
- web/pom.xml
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/ProductController.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/ProductControllerTest.java
> Update onboarding product lib

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/CheckManagerResponse.java
- web/src/main/resources/swagger/swagger_en.properties
changed check manager response property response to result
> [PNPG-263] fix: changed check manager response property response to result

- app/src/main/resources/swagger/api-docs.json
- connector-api/pom.xml
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- core/pom.xml
- web/pom.xml
Added new institutionType GPU
Updated dependency of commons
> [SELC-5610] feat: Updated dependencies for new libs

- connector-api/pom.xml
- core/pom.xml
- web/pom.xml
Updated sdk of common to 0.5.1
> feat: Updated sdk common

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/BusinessData.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/GPUData.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionUpdate.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/PaymentServiceProvider.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/InstitutionResponse.java
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitution.json
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitutionUsingExternalId.json
- connector/rest/src/test/resources/stubs/party-process/mappings/getUserInstitutionRelationships_fullyValued.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingProductDto.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
- web/src/main/resources/swagger/swagger_en.properties
- Added new class BusinessData
- Added new class GPUData
- Refactored class PSP
Added new value for GPU
> [SELC-5513] feat: Added new fields for GPUData

- app/src/main/resources/swagger/api-docs.json
- pom.xml
Updated commons lib
Updated InstitutionType for GPU
> [SELC-5513] bug-fix: Updated commons lib

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Added API to retrieve attachment for a given onboarding according to its name
This API is necessary to complete the onboarding process for a GPU institution
I have deployed the feature branch in DEV and tested the api /v2/tokens/{onboardingId}/attachment?name={name}
> [SELC-6131] feat: Added api to retrieve attachment by onboarding id

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/BusinessData.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/GPUData.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
Added field **longTermPayments** for GPU onboarding
This change is necessary to store the new field and display it into report
I have deployed the feature branch in DEV and tested the api for onboarding POST /onboarding
> [SELC-6169] feat: added field for GPU onboarding request

- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
Modified management to populate user and admin field
From the FE the information was being displayed the wrong way
dev - local
> [SELC-5352] feat: Fixed array user-admin

- connector-api/pom.xml
- core/pom.xml
- web/pom.xml
> [SELC-6160] feat: Update SDK dependency

- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/ManagerVerification.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/utils/PgManagerVerifier.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/utils/Utils.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/utils/PgManagerVerifierTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/utils/UtilsTest.java
added implementation of new API to find manager data given onboardingId
local env
> [SELC-6181] feat: added implementation of new API to find manager data given onboardingId

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionOnboardingResource.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/model/InstitutionOnboardingResourceTest.java
> feat: added business name

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfigTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
Fixed endpoint to match param-case format
Added exclusion of junit test for api-docs
Updated manually api-docs
> [SELC-6096] feat: Fixed endpoint "/onboarding/recipient-code/verification"

- .github/workflows/create_release_branch.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_open_api.yml
update ubuntu from 20.04 to 24.04
version 20.04 will be deprecated soon
> feat: update ubuntu from 20.04 to 24.04

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfigTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfig.java
- web/src/main/resources/swagger/swagger_en.properties
> [SELC-6727] fix: Fixed method of configuration of swagger

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
Fixed description and summary for endpoint /v2/tokens/{onboardingId}/reject
> [SELC-6100] feat: Update endpoint config /v2/tokens/{onboardingId}/reject

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
Updated endpoint description and summary v2/tokens/{onboardingId}/reject
> [SELC-6100] feat: Update release branch

- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
Added ref to a new variable populated by kv
Preventing bola attack
> [SELC-6669] feat: Added variable user-allowed-list from KV

- .gitignore
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/exceptions/UnauthorizedUserException.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategy.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategyImpl.java
- core/src/main/resources/config/core-config.properties
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategyTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/handler/TokenExceptionHandler.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/handler/TokenExceptionHandlerTest.java
Added custom method to handle exception for unauthorized user (403)
added service for verifying uid of manager or delegate user and checking to see if uid is present in the list of censored people
Preventing bola attack!
local env
> [SELC-6670] feat: Added security layer on /{onboardingId}/products/{productId}/aggregates-csv (BOLA)

- .gitignore
- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/exceptions/UnauthorizedUserException.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/MsOnboardingInternalApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/MsOnboardingApiClientConfig.java
- connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategy.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategyImpl.java
- core/src/main/resources/config/core-config.properties
- core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/strategy/UserAllowedValidationStrategyTest.java
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/handler/TokenExceptionHandler.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/handler/TokenExceptionHandlerTest.java
> Update release branch with main

- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/UserInstitutionConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/userInstitution/UserInstitutionRequest.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/userInstitution/UserInstitutionResponse.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/MsUserInstitutionConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/MsUserInstitutionApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/MsUserInstitutionApiClientConfig.java
- connector/rest/src/main/resources/config/ms-user-institution-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/MsUserInstitutionConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserInstitutionService.java
- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserInstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserInstitutionServiceImplTest.java
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Added method to check at onboarding completed users within user institution
Added client to invoke userInstitution
Preventing bola attack!
dev
> [SELC-6809] feat: Added method to check at onboarding completed users within user institution

- core/src/main/java/it/pagopa/selfcare/onboarding/core/UserInstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/onboarding/core/UserInstitutionServiceImplTest.java
Fixed filter for service
Added utility to return list of 
local - dev
> [SELC-6809] feat: Added utility method to prepare filter for query

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfigTest.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/AggregateResult.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/MsOnboardingBillingApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/config/MsOnboardingApiClientConfig.java
- connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/AggregateInstitution.java
- remove fields taxCodePT, service, syncAsyncMode from verify aggregates csv for prod pagopa
The mentioned fields are no longer needed in aggregates csv for prod pagopa
It was tested locally
> [SELC-6409] feat: remove unused fields from verify aggregates csv

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/onboarding/web/config/SwaggerConfig.java
Fixed config of swagger interface because base path was wrong
local - dev
> Fixed swagger ui

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/InstitutionInfo.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/InstitutionUpdate.java
- connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingResponseData.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/BillingDataResponse.java
- connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/InstitutionResponse.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionData.java
- web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingDto.java
- web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
Added new institutionType SCEC
Updated into bean ref to onboarding-sdk-commons
Updated  open-api
> [SELC-7790] feat: Updated sdk with new institutionType
